"""add_customers_domain

Revision ID: 39f9e2867723
Revises: 889c19af954b
Create Date: 2026-07-17 13:20:20.417452
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f9e2867723'
down_revision: Union[str, None] = '889c19af954b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_customers_tenant_email')
    )
    op.create_index('idx_customers_tenant_active', 'customers', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_customers_tenant_email', 'customers', ['tenant_id', 'email'], unique=False)
    op.create_index('idx_customers_tenant_id', 'customers', ['tenant_id'], unique=False)
    op.create_index('idx_customers_tenant_name', 'customers', ['tenant_id', 'last_name', 'first_name'], unique=False)
    op.create_index('idx_customers_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=False)
    op.create_table('customer_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_notes_customer', 'customer_notes', ['customer_id'], unique=False)
    op.create_index('idx_customer_notes_tenant', 'customer_notes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customer_notes_tenant', table_name='customer_notes')
    op.drop_index('idx_customer_notes_customer', table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index('idx_customers_tenant_phone', table_name='customers')
    op.drop_index('idx_customers_tenant_name', table_name='customers')
    op.drop_index('idx_customers_tenant_id', table_name='customers')
    op.drop_index('idx_customers_tenant_email', table_name='customers')
    op.drop_index('idx_customers_tenant_active', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
