"""add_appointments_domain

Revision ID: 3c8d681e0f21
Revises: afd7ffc0766e
Create Date: 2026-07-17 14:28:29.580166
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8d681e0f21'
down_revision: Union[str, None] = 'afd7ffc0766e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_assigned_to', 'appointments', ['assigned_to'], unique=False)
    op.create_index('idx_appointments_customer_id', 'appointments', ['customer_id'], unique=False)
    op.create_index('idx_appointments_tenant_id', 'appointments', ['tenant_id'], unique=False)
    op.create_index('idx_appointments_tenant_scheduled', 'appointments', ['tenant_id', 'scheduled_at'], unique=False)
    op.create_index('idx_appointments_tenant_status', 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index('idx_appointments_tenant_status', table_name='appointments')
    op.drop_index('idx_appointments_tenant_scheduled', table_name='appointments')
    op.drop_index('idx_appointments_tenant_id', table_name='appointments')
    op.drop_index('idx_appointments_customer_id', table_name='appointments')
    op.drop_index('idx_appointments_assigned_to', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
